// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/logica/AnalizadorLexico.flex

package code;

import compilerTools.Token;
import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;


@SuppressWarnings("fallthrough")
class AnalizadorLexico {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\1\u0400\266\u0200\10\u0500\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\1"+
    "\1\5\1\6\1\7\1\0\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\12\23"+
    "\1\24\1\25\1\26\1\27\1\30\2\0\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\42\1\51"+
    "\1\52\1\53\1\54\1\55\1\56\1\57\1\60\1\42"+
    "\1\61\1\0\1\62\1\0\1\42\1\0\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\42\1\51"+
    "\1\52\1\53\1\54\1\55\1\56\1\57\1\60\1\42"+
    "\1\63\1\0\1\64\1\65\6\0\1\3\252\0\2\66"+
    "\115\0\1\67\u01a8\0\2\3\u0100\0\1\70\325\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\3\2\1\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\16\21\1\22\1\23\1\24\1\25"+
    "\1\26\2\1\1\0\1\27\1\30\1\31\1\0\1\32"+
    "\1\0\1\2\3\0\1\33\1\0\1\34\1\35\1\36"+
    "\1\37\1\40\4\21\1\0\2\21\1\0\3\21\1\0"+
    "\3\21\1\0\4\21\1\41\1\21\1\41\2\21\2\0"+
    "\1\42\1\43\2\2\1\44\1\45\1\46\1\47\1\21"+
    "\1\50\1\21\1\0\3\21\1\0\3\21\1\0\2\21"+
    "\2\51\1\21\1\0\1\21\1\0\1\21\1\0\3\21"+
    "\1\0\3\21\2\0\1\21\1\52\1\2\1\0\1\2"+
    "\1\21\2\53\2\21\1\0\1\21\1\0\1\21\1\0"+
    "\2\21\1\0\2\21\1\0\1\21\1\0\1\21\1\0"+
    "\2\54\1\55\1\21\1\0\1\21\1\0\1\21\1\0"+
    "\1\56\1\21\1\0\1\56\1\21\1\2\2\0\2\57"+
    "\1\21\2\60\1\61\1\0\1\21\1\0\1\21\2\62"+
    "\1\21\2\63\2\64\1\21\1\0\1\21\1\0\1\21"+
    "\1\0\1\21\1\0\1\21\1\0\1\65\1\2\2\0"+
    "\2\66\1\21\1\0\1\21\1\67\2\70\2\71\1\21"+
    "\1\0\2\72\2\73\1\2\2\74\1\75\2\76";

  private static int [] zzUnpackAction() {
    int [] result = new int[221];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\71\0\162\0\253\0\344\0\u011d\0\u0156"+
    "\0\71\0\71\0\u018f\0\u01c8\0\71\0\u0201\0\71\0\u023a"+
    "\0\u0273\0\u02ac\0\71\0\u02e5\0\u031e\0\u0357\0\u0390\0\u03c9"+
    "\0\u0402\0\u043b\0\u0474\0\u04ad\0\u04e6\0\u051f\0\u0558\0\u0591"+
    "\0\u05ca\0\u0603\0\u063c\0\71\0\71\0\71\0\71\0\71"+
    "\0\u0675\0\u06ae\0\253\0\71\0\71\0\71\0\u06e7\0\71"+
    "\0\u0720\0\u0759\0\u0792\0\u07cb\0\u0804\0\71\0\u083d\0\71"+
    "\0\71\0\71\0\71\0\71\0\u0876\0\u08af\0\u08e8\0\u0921"+
    "\0\u095a\0\u0993\0\u09cc\0\u0a05\0\u0a3e\0\u0a77\0\u0ab0\0\u0ae9"+
    "\0\u0b22\0\u0b5b\0\u0b94\0\u0bcd\0\u0c06\0\u0c3f\0\u0c78\0\u0cb1"+
    "\0\u0cea\0\u0d23\0\u0d5c\0\u0d95\0\u0dce\0\u0e07\0\u0e40\0\71"+
    "\0\71\0\u0e79\0\u0eb2\0\71\0\71\0\71\0\u083d\0\u0eeb"+
    "\0\u0357\0\u0f24\0\u0f5d\0\u0f96\0\u0fcf\0\u1008\0\u1041\0\u107a"+
    "\0\u10b3\0\u10ec\0\u1125\0\u115e\0\u1197\0\u0357\0\71\0\u11d0"+
    "\0\u1209\0\u1242\0\u127b\0\u12b4\0\u12ed\0\u1326\0\u135f\0\u1398"+
    "\0\u13d1\0\u140a\0\u1443\0\u147c\0\u14b5\0\u14ee\0\u1527\0\u0357"+
    "\0\u1560\0\u1599\0\u15d2\0\u160b\0\u0357\0\71\0\u1644\0\u167d"+
    "\0\u16b6\0\u16ef\0\u1728\0\u1761\0\u179a\0\u17d3\0\u180c\0\u1845"+
    "\0\u187e\0\u18b7\0\u18f0\0\u1929\0\u1962\0\u199b\0\u19d4\0\u0357"+
    "\0\71\0\u0357\0\u1a0d\0\u1a46\0\u1a7f\0\u1ab8\0\u1af1\0\u1b2a"+
    "\0\u0357\0\u1b63\0\u1b9c\0\71\0\u1bd5\0\u1c0e\0\u1c47\0\u1c80"+
    "\0\u0357\0\71\0\u1cb9\0\u0357\0\71\0\u0357\0\u1cf2\0\u1d2b"+
    "\0\u1d64\0\u1d9d\0\u0357\0\71\0\u1dd6\0\u0357\0\71\0\u0357"+
    "\0\71\0\u1e0f\0\u1e48\0\u1e81\0\u1eba\0\u1ef3\0\u1f2c\0\u1f65"+
    "\0\u1f9e\0\u1fd7\0\u2010\0\u0357\0\u2049\0\u2082\0\u20bb\0\u0357"+
    "\0\71\0\u20f4\0\u212d\0\u2166\0\u0357\0\u0357\0\71\0\u0357"+
    "\0\71\0\u219f\0\u21d8\0\u0357\0\71\0\u0357\0\71\0\u1599"+
    "\0\u0357\0\71\0\u0357\0\u0357\0\71";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[221];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\2\1\5\1\2\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\2\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\26\1\34"+
    "\1\35\2\26\1\36\1\37\3\26\1\40\1\41\1\42"+
    "\1\26\1\43\3\26\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\2\73\0\1\3\66\0\2\53\1\0"+
    "\1\53\1\0\1\53\1\54\62\53\10\0\1\55\76\0"+
    "\1\56\52\0\2\57\1\0\1\57\1\0\64\57\15\0"+
    "\1\60\71\0\1\61\61\0\1\62\10\0\1\63\26\0"+
    "\1\64\10\0\1\65\32\0\1\66\67\0\1\67\1\0"+
    "\1\21\52\0\1\70\16\0\1\71\2\0\1\72\70\0"+
    "\1\73\70\0\1\74\64\0\1\26\5\0\30\26\33\0"+
    "\1\26\5\0\20\26\1\75\7\26\33\0\1\26\5\0"+
    "\1\76\7\26\1\77\5\26\1\100\11\26\5\0\1\101"+
    "\25\0\1\26\5\0\4\26\1\102\3\26\1\103\17\26"+
    "\5\0\1\104\25\0\1\26\5\0\15\26\1\105\12\26"+
    "\33\0\1\26\5\0\1\106\7\26\1\107\17\26\5\0"+
    "\1\110\25\0\1\26\5\0\1\111\27\26\33\0\1\26"+
    "\5\0\15\26\1\112\3\26\1\113\6\26\6\0\1\114"+
    "\24\0\1\26\5\0\4\26\1\115\11\26\1\116\11\26"+
    "\33\0\1\26\5\0\16\26\1\117\11\26\33\0\1\26"+
    "\5\0\4\26\1\120\23\26\33\0\1\26\5\0\10\26"+
    "\1\121\14\26\1\122\2\26\5\0\1\123\25\0\1\26"+
    "\5\0\4\26\1\124\23\26\33\0\1\26\5\0\1\125"+
    "\27\26\56\0\1\126\3\0\1\114\14\0\1\114\42\0"+
    "\1\123\14\0\1\127\7\0\1\123\14\0\1\130\106\0"+
    "\1\131\40\0\2\132\1\0\1\132\1\0\54\132\1\133"+
    "\7\132\26\0\1\134\62\0\1\135\70\0\1\136\73\0"+
    "\1\137\70\0\1\26\5\0\4\26\1\140\23\26\33\0"+
    "\1\26\5\0\20\26\1\141\1\142\6\26\6\0\1\143"+
    "\24\0\1\26\5\0\4\26\1\144\23\26\33\0\1\26"+
    "\5\0\15\26\1\145\2\26\1\146\7\26\45\0\1\147"+
    "\56\0\1\26\5\0\2\26\1\150\2\26\1\151\22\26"+
    "\33\0\1\26\5\0\4\26\1\152\23\26\45\0\1\153"+
    "\56\0\1\26\5\0\22\26\1\154\5\26\33\0\1\26"+
    "\5\0\13\26\1\155\14\26\33\0\1\26\5\0\15\26"+
    "\1\156\12\26\56\0\1\157\45\0\1\26\5\0\21\26"+
    "\1\160\6\26\6\0\1\161\24\0\1\26\5\0\10\26"+
    "\1\162\17\26\5\0\1\163\25\0\1\26\5\0\1\164"+
    "\27\26\41\0\1\165\62\0\1\26\5\0\4\26\1\166"+
    "\23\26\33\0\1\26\5\0\6\26\1\167\21\26\33\0"+
    "\1\26\5\0\21\26\1\170\6\26\6\0\1\171\24\0"+
    "\1\26\5\0\17\26\1\172\10\26\33\0\1\26\5\0"+
    "\15\26\1\173\12\26\33\0\1\26\5\0\10\26\1\174"+
    "\17\26\5\0\1\175\50\0\1\176\45\0\1\26\5\0"+
    "\26\26\1\177\1\26\33\0\1\26\5\0\20\26\1\200"+
    "\7\26\51\0\1\163\24\0\1\163\43\0\1\175\24\0"+
    "\1\175\2\0\2\132\1\0\1\132\1\0\64\132\2\201"+
    "\1\202\1\201\1\202\55\201\1\203\6\201\23\0\1\26"+
    "\5\0\1\204\27\26\33\0\1\26\5\0\4\26\1\205"+
    "\23\26\45\0\1\206\56\0\1\26\5\0\20\26\1\207"+
    "\7\26\33\0\1\26\5\0\21\26\1\210\6\26\6\0"+
    "\1\211\24\0\1\26\5\0\22\26\1\212\5\26\61\0"+
    "\1\213\42\0\1\26\5\0\10\26\1\214\17\26\5\0"+
    "\1\215\25\0\1\26\5\0\1\216\27\26\33\0\1\26"+
    "\5\0\6\26\1\217\21\26\47\0\1\220\54\0\1\26"+
    "\5\0\4\26\1\221\23\26\33\0\1\26\5\0\21\26"+
    "\1\222\6\26\6\0\1\223\24\0\1\26\5\0\22\26"+
    "\1\224\5\26\63\0\1\225\40\0\1\26\5\0\2\26"+
    "\1\226\25\26\43\0\1\227\60\0\1\26\5\0\2\26"+
    "\1\230\25\26\43\0\1\231\60\0\1\26\5\0\20\26"+
    "\1\232\7\26\33\0\1\26\5\0\10\26\1\233\17\26"+
    "\5\0\1\234\25\0\1\26\5\0\22\26\1\235\5\26"+
    "\63\0\1\236\40\0\1\26\5\0\10\26\1\237\17\26"+
    "\5\0\1\240\25\0\1\26\5\0\16\26\1\241\11\26"+
    "\33\0\1\26\5\0\22\26\1\242\5\26\63\0\1\243"+
    "\64\0\1\244\44\0\1\26\5\0\22\26\1\245\5\26"+
    "\10\0\2\132\1\0\1\132\1\0\55\132\1\246\6\132"+
    "\62\0\1\247\6\0\2\133\1\250\1\133\1\250\2\133"+
    "\1\132\52\133\1\246\6\133\23\0\1\26\5\0\12\26"+
    "\1\251\15\26\7\0\1\252\23\0\1\26\5\0\22\26"+
    "\1\253\5\26\33\0\1\26\5\0\22\26\1\254\5\26"+
    "\63\0\1\255\40\0\1\26\5\0\16\26\1\256\11\26"+
    "\63\0\1\257\40\0\1\26\5\0\14\26\1\260\13\26"+
    "\55\0\1\261\46\0\1\26\5\0\23\26\1\262\4\26"+
    "\33\0\1\26\5\0\16\26\1\263\11\26\57\0\1\264"+
    "\44\0\1\26\5\0\20\26\1\265\7\26\33\0\1\26"+
    "\5\0\16\26\1\266\11\26\57\0\1\267\44\0\1\26"+
    "\5\0\1\270\27\26\41\0\1\271\62\0\1\26\5\0"+
    "\10\26\1\272\17\26\5\0\1\273\43\0\1\273\24\0"+
    "\1\273\25\0\1\26\5\0\2\26\1\274\25\26\43\0"+
    "\1\275\60\0\1\26\5\0\20\26\1\276\7\26\61\0"+
    "\1\277\42\0\1\26\5\0\22\26\1\300\5\26\63\0"+
    "\1\301\40\0\1\26\5\0\2\26\1\302\25\26\43\0"+
    "\1\303\60\0\1\26\5\0\16\26\1\304\11\26\10\0"+
    "\2\201\1\202\1\201\1\202\55\201\1\305\6\201\62\202"+
    "\1\306\70\202\1\307\6\202\23\0\1\26\5\0\16\26"+
    "\1\310\11\26\57\0\1\311\44\0\1\26\5\0\1\312"+
    "\27\26\41\0\1\313\62\0\1\26\5\0\13\26\1\314"+
    "\14\26\33\0\1\26\5\0\16\26\1\315\11\26\33\0"+
    "\1\26\5\0\16\26\1\316\11\26\57\0\1\317\44\0"+
    "\1\26\5\0\16\26\1\320\11\26\57\0\1\321\44\0"+
    "\1\26\5\0\1\322\27\26\41\0\1\323\62\0\1\26"+
    "\5\0\4\26\1\324\23\26\45\0\1\325\56\0\1\26"+
    "\5\0\7\26\1\326\20\26\50\0\1\327\30\0\2\246"+
    "\1\247\1\246\1\247\2\246\1\201\52\246\1\305\6\246"+
    "\7\247\1\330\52\247\1\306\6\247\7\250\1\3\52\250"+
    "\1\247\6\250\23\0\1\26\5\0\13\26\1\331\14\26"+
    "\54\0\1\332\47\0\1\26\5\0\22\26\1\333\5\26"+
    "\33\0\1\26\5\0\20\26\1\334\7\26\61\0\1\335"+
    "\17\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[8721];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\5\1\2\11\2\1\1\11\1\1\1\11"+
    "\3\1\1\11\20\1\5\11\2\1\1\0\3\11\1\0"+
    "\1\11\1\0\1\1\3\0\1\11\1\0\5\11\4\1"+
    "\1\0\2\1\1\0\3\1\1\0\3\1\1\0\11\1"+
    "\2\0\2\11\2\1\3\11\4\1\1\0\3\1\1\0"+
    "\3\1\1\0\3\1\1\11\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\3\1\1\0\3\1\2\0\3\1\1\0"+
    "\3\1\1\11\2\1\1\0\1\1\1\0\1\1\1\0"+
    "\2\1\1\0\2\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\11\2\1\1\0\1\1\1\0\1\1\1\0"+
    "\2\1\1\0\1\11\2\1\2\0\1\1\1\11\2\1"+
    "\1\11\1\1\1\0\1\1\1\0\2\1\1\11\2\1"+
    "\1\11\1\1\1\11\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\2\1\2\0\1\1"+
    "\1\11\1\1\1\0\3\1\1\11\1\1\1\11\1\1"+
    "\1\0\1\1\1\11\1\1\1\11\2\1\1\11\2\1"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[221];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
  private Token token(String lexema, String componenteLexico, int line, int column)
   {
    return new Token(lexema, componenteLexico, line+1, column+1);
   }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AnalizadorLexico(java.io.Reader in) {
      //Seccion del Constructor  
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.err.println("LEX ERROR: " + yytext() + " at " + (yyline+1) + ":" + (yycolumn+1)); /* no return */
            }
          // fall through
          case 63: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 64: break;
          case 3:
            { return token(yytext(),"MODULO",yyline,yycolumn);
            }
          // fall through
          case 65: break;
          case 4:
            { return token(yytext(), "PAREN_IZQ", yyline, yycolumn);
            }
          // fall through
          case 66: break;
          case 5:
            { return token(yytext(), "PAREN_DER", yyline, yycolumn);
            }
          // fall through
          case 67: break;
          case 6:
            { return token(yytext(),"MULTIPLICACION",yyline,yycolumn);
            }
          // fall through
          case 68: break;
          case 7:
            { return token(yytext(),"SUMA",yyline,yycolumn);
            }
          // fall through
          case 69: break;
          case 8:
            { return token(yytext(), "COMA", yyline, yycolumn);
            }
          // fall through
          case 70: break;
          case 9:
            { return token(yytext(),"RESTA",yyline,yycolumn);
            }
          // fall through
          case 71: break;
          case 10:
            { return token(yytext(), "PUNTO", yyline, yycolumn);
            }
          // fall through
          case 72: break;
          case 11:
            { return token(yytext(),"DIVISION",yyline,yycolumn);
            }
          // fall through
          case 73: break;
          case 12:
            { return token(yytext(),"ENTERO",yyline,yycolumn);
            }
          // fall through
          case 74: break;
          case 13:
            { return token(yytext(), "DOS_PUNTOS", yyline, yycolumn);
            }
          // fall through
          case 75: break;
          case 14:
            { return token(yytext(), "PUNTO_COMA", yyline, yycolumn);
            }
          // fall through
          case 76: break;
          case 15:
            { return token(yytext(),"OP_MENOR",yyline,yycolumn);
            }
          // fall through
          case 77: break;
          case 16:
            { return token(yytext(),"OP_MAYOR",yyline,yycolumn);
            }
          // fall through
          case 78: break;
          case 17:
            { return token(yytext(),"IDENTIFICADOR",yyline,yycolumn);
            }
          // fall through
          case 79: break;
          case 18:
            { return token(yytext(),"CORCH_IZQ",yyline,yycolumn);
            }
          // fall through
          case 80: break;
          case 19:
            { return token(yytext(),"CORCH_DER",yyline,yycolumn);
            }
          // fall through
          case 81: break;
          case 20:
            { return token(yytext(), "LLAVE_IZQ", yyline, yycolumn);
            }
          // fall through
          case 82: break;
          case 21:
            { return token(yytext(), "LLAVE_DER", yyline, yycolumn);
            }
          // fall through
          case 83: break;
          case 22:
            { return token(yytext(),"LOGICO_NOT",yyline,yycolumn);
            }
          // fall through
          case 84: break;
          case 23:
            { return token(yytext(),"CADENA",yyline,yycolumn);
            }
          // fall through
          case 85: break;
          case 24:
            { return token(yytext(),"OP_MOD_MOD",yyline,yycolumn);
            }
          // fall through
          case 86: break;
          case 25:
            { return token(yytext(),"CONCAT",yyline,yycolumn);
            }
          // fall through
          case 87: break;
          case 26:
            { return token(yytext(),"OP_MULT_MULTI",yyline,yycolumn);
            }
          // fall through
          case 88: break;
          case 27:
            { return token(yytext(),"OP_DIV_DIV",yyline,yycolumn);
            }
          // fall through
          case 89: break;
          case 28:
            { return token(yytext(),"OP_DIFERENTE",yyline,yycolumn);
            }
          // fall through
          case 90: break;
          case 29:
            { return token(yytext(),"OP_IGUAL_IGUAL",yyline,yycolumn);
            }
          // fall through
          case 91: break;
          case 30:
            { return token(yytext(),"ASIGNACION",yyline,yycolumn);
            }
          // fall through
          case 92: break;
          case 31:
            { return token(yytext(),"OP_MENOR_IGUAL",yyline,yycolumn);
            }
          // fall through
          case 93: break;
          case 32:
            { return token(yytext(),"OP_MAYOR_IGUAL",yyline,yycolumn);
            }
          // fall through
          case 94: break;
          case 33:
            { return token(yytext(),"SI",yyline,yycolumn);
            }
          // fall through
          case 95: break;
          case 34:
            { return token(yytext(),"CARACTER",yyline,yycolumn);
            }
          // fall through
          case 96: break;
          case 35:
            { return token(yytext(),"OP_INCREMENTO",yyline,yycolumn);
            }
          // fall through
          case 97: break;
          case 36:
            { return token(yytext(),"OP_DECREMENTO",yyline,yycolumn);
            }
          // fall through
          case 98: break;
          case 37:
            { return token(yytext(),"LOGICO_OR",yyline,yycolumn);
            }
          // fall through
          case 99: break;
          case 38:
            { return token(yytext(),"LOGICO_AND",yyline,yycolumn);
            }
          // fall through
          case 100: break;
          case 39:
            { return token(yytext(),"FLOTANTE",yyline,yycolumn);
            }
          // fall through
          case 101: break;
          case 40:
            { return token(yytext(),"TIPO_CAR",yyline,yycolumn);
            }
          // fall through
          case 102: break;
          case 41:
            { return token(yytext(),"FIN",yyline,yycolumn);
            }
          // fall through
          case 103: break;
          case 42:
            { return token(yytext(),"VAR",yyline,yycolumn);
            }
          // fall through
          case 104: break;
          case 43:
            { return token(yytext(),"CASE",yyline,yycolumn);
            }
          // fall through
          case 105: break;
          case 44:
            { return token(yytext(),"FOR",yyline,yycolumn);
            }
          // fall through
          case 106: break;
          case 45:
            { return token(yytext(),"LEER",yyline,yycolumn);
            }
          // fall through
          case 107: break;
          case 46:
            { return token(yytext(),"SINO",yyline,yycolumn);
            }
          // fall through
          case 108: break;
          case 47:
            { return token(yytext(),"BREAK",yyline,yycolumn);
            }
          // fall through
          case 109: break;
          case 48:
            { return token(yytext(),"CONST",yyline,yycolumn);
            }
          // fall through
          case 110: break;
          case 49:
            { return token(yytext(),"TIPO_CORTO",yyline,yycolumn);
            }
          // fall through
          case 111: break;
          case 50:
            { return token(yytext(),"WHILE",yyline,yycolumn);
            }
          // fall through
          case 112: break;
          case 51:
            { return token(yytext(),"BOOLEAN_FALSE",yyline,yycolumn);
            }
          // fall through
          case 113: break;
          case 52:
            { return token(yytext(),"HASTA",yyline,yycolumn);
            }
          // fall through
          case 114: break;
          case 53:
            { return token(yytext(),"TIPO_TEXTO",yyline,yycolumn);
            }
          // fall through
          case 115: break;
          case 54:
            { return token(yytext(),"BOOLEAN_TRUE",yyline,yycolumn);
            }
          // fall through
          case 116: break;
          case 55:
            { return token(yytext(),"TIPO_ENTERO",yyline,yycolumn);
            }
          // fall through
          case 117: break;
          case 56:
            { return token(yytext(),"INICIO",yyline,yycolumn);
            }
          // fall through
          case 118: break;
          case 57:
            { return token(yytext(),"TIPO_LOGICO",yyline,yycolumn);
            }
          // fall through
          case 119: break;
          case 58:
            { return token(yytext(),"REPITE",yyline,yycolumn);
            }
          // fall through
          case 120: break;
          case 59:
            { return token(yytext(),"SWITCH",yyline,yycolumn);
            }
          // fall through
          case 121: break;
          case 60:
            { return token(yytext(),"TIPO_DECIMAL",yyline,yycolumn);
            }
          // fall through
          case 122: break;
          case 61:
            { return token(yytext(),"DEFAULT",yyline,yycolumn);
            }
          // fall through
          case 123: break;
          case 62:
            { return token(yytext(),"MOSTRAR",yyline,yycolumn);
            }
          // fall through
          case 124: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
